server {
    listen 80;
    listen [::]:80;
    
    server_name segnec.com.ar www.segnec.com.ar;

    root /var/www/segnec.com.ar;
    index index.html index.htm;

    # Permitir solicitudes para Let's Encrypt (Certbot)
    location ~ /.well-known/acme-challenge {
        allow all;
        root /var/www/segnec.com.ar;
    }

    # Resto del tráfico HTTP redirigirlo a HTTPS (Lo descomentas cuando ya tengas el cert generado)
    # return 301 https://$host$request_uri;

    location / {
        try_files $uri $uri/ =404;
    }

    # Soporte para PHP (Agregado para el formulario de contacto)
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }
}

# Bloque HTTPS (Descomentar cuando hayas ejecutado certbot)
# server {
#     listen 443 ssl http2;
#     listen [::]:443 ssl http2;
#     server_name segnec.com.ar www.segnec.com.ar;
# 
#     root /var/www/segnec.com.ar;
#     index index.html index.htm;
# 
#     ssl_certificate /etc/letsencrypt/live/segnec.com.ar/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/segnec.com.ar/privkey.pem;
#     
#     # Seguridad recomendada SSL
#     ssl_protocols TLSv1.2 TLSv1.3;
#     ssl_prefer_server_ciphers on;
# 
#     location / {
#         try_files $uri $uri/ =404;
#     }
# }
